version: '3.4'

networks:
  services:
    external:
      name: services

volumes:
  # volumes for nzbhydra services
  usenet-nzbhydra-complete:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.hutter.cloud,rw,nolock,async
      device: ":/volume1/docker/usenet-sabnzbd-complete/nzbhydra"
  usenet-nzbhydra-config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.hutter.cloud,rw,nolock,async
      device: ":/volume1/docker/usenet-nzbhydra-config"
  usenet-nzbhydra-nzb:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.hutter.cloud,rw,nolock,async
      device: ":/volume1/docker/usenet-nzbhydra-nzb"

  # volumes for sabnzbd container
  usenet-sabnzbd-incomplete:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.hutter.cloud,rw,nolock,async
      device: ":/volume1/docker/usenet-sabnzbd-incomplete"
  usenet-sabnzbd-complete:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.hutter.cloud,rw,nolock,async
      device: ":/volume1/docker/usenet-sabnzbd-complete"
  usenet-sabnzbd-logs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.hutter.cloud,rw,nolock,async
      device: ":/volume1/docker/usenet-sabnzbd-logs"
  usenet-sabnzbd-admin:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.hutter.cloud,rw,nolock,async
      device: ":/volume1/docker/usenet-sabnzbd-admin"

  # media library
  usenet-library:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.hutter.cloud,rw,nolock,async
      device: ":/volume1/library"
  usenet-library-tv:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.hutter.cloud,rw,nolock,async
      device: ":/volume1/library/tv"
  usenet-library-tv-de:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.hutter.cloud,rw,nolock,async
      device: ":/volume1/library/tv_de"
  usenet-library-music:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.hutter.cloud,rw,nolock,async
      device: ":/volume1/library/music"

  # volumes for couchpotato
  usenet-couchpotato-logs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.hutter.cloud,rw,nolock,async
      device: ":/volume1/docker/usenet-couchpotato-logs"
  usenet-couchpotato-plugins:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.hutter.cloud,rw,nolock,async
      device: ":/volume1/docker/usenet-couchpotato-plugins"
  usenet-couchpotato-db_backup:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.hutter.cloud,rw,nolock,async
      device: ":/volume1/docker/usenet-couchpotato-db_backup"
  usenet-couchpotato-database:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.hutter.cloud,rw,nolock,async
      device: ":/volume1/docker/usenet-couchpotato-database"
  usenet-couchpotato-cache:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.hutter.cloud,rw,nolock,async
      device: ":/volume1/docker/usenet-couchpotato-cache"

  # volumes for sonarr
  usenet-sonarr-conf:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.hutter.cloud,rw,nolock,async
      device: ":/volume1/docker/usenet-sonarr-conf"

  # volumes for headphones
  usenet-headphones-config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.hutter.cloud,rw,nolock,async
      device: ":/volume1/docker/usenet-headphones-config"

services:
  # reverse proxy handling incoming connections from our connectivity haproxy
  homepage:
    image: sebastianhutter/nginx:latest
    networks:
      - services
    environment:
      CONFIG_URL: http://nas.hutter.cloud/dnas/docker/usenet/nginx.conf
      INDEX_URL: http://nas.barfoot.local/dnas/docker/usenet/index.html
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.tags=back"
        - "traefik.backend=usenet-homepage"
        - "traefik.frontend.entryPoints=http"
        - "traefik.frontend.rule=Host:usenet.hutter.cloud"
        - "traefik.protocol=http"
        - "traefik.docker.network=services"
        - "traefik.port=80"


  # nzbhydra services
  nzbhydra-browser:
    image: sebastianhutter/elfinder:latest
    environment:
      ELFINDER_FILES_URI: /nzbhydra-browser/files
    stdin_open: true
    volumes:
      - usenet-nzbhydra-complete:/var/www/html/files
    networks:
      - services
    tty: true
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.tags=back"
        - "traefik.backend=usenet-hydra-browser"
        - "traefik.frontend.entryPoints=http"
        - "traefik.frontend.rule=Host:usenet.hutter.cloud;PathPrefixStrip:/nzbhydra-browser"
        - "traefik.protocol=http"
        - "traefik.docker.network=services"
        - "traefik.port=80"

  nzbhydra:
    image: linuxserver/hydra
    stdin_open: true
    volumes:
      - usenet-nzbhydra-config:/config
      - usenet-nzbhydra-nzb:/downloads
    networks:
      - services
    tty: true
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.tags=back"
        - "traefik.backend=usenet-hydra"
        - "traefik.frontend.entryPoints=http"
        - "traefik.frontend.rule=Host:usenet.hutter.cloud;PathPrefix:/nzbhydra"
        - "traefik.protocol=http"
        - "traefik.docker.network=services"
        - "traefik.port=5075"

  # usenet services
  sabnzbd:
    image: sebastianhutter/sabnzbd:latest
    environment:
      SABNZBD_CONFIG_URL: http://nas.barfoot.local/dnas/docker/usenet/sabnzbd.ini
      NZBTOMEDIA_CONFIG_URL: http://nas.barfoot.local/dnas/docker/usenet/autoProcessMedia.cfg
    stdin_open: true
    volumes:
      - usenet-sabnzbd-admin:/sabnzbd/admin
      - usenet-sabnzbd-complete:/sabnzbd/Downloads/complete
      - usenet-sabnzbd-incomplete:/sabnzbd/Downloads/incomplete
      - usenet-sabnzbd-logs:/sabnzbd/logs
    networks:
      - services
    tty: true
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.tags=back"
        - "traefik.backend=usenet-sabnzbd"
        - "traefik.frontend.entryPoints=http"
        - "traefik.frontend.rule=Host:usenet.hutter.cloud;PathPrefix:/sabnzbd"
        - "traefik.protocol=http"
        - "traefik.docker.network=services"
        - "traefik.port=8085"

  couchpotato:
    image: sebastianhutter/couchpotato:latest
    environment:
      COUCHPOTATO_CONFIG_URL: http://nas.barfoot.local/dnas/docker/usenet/settings.conf
    stdin_open: true
    volumes:
      - usenet-couchpotato-cache:/CouchPotatoServer/cache
      - usenet-couchpotato-plugins:/CouchPotatoServer/custom_plugins
      - usenet-couchpotato-database:/CouchPotatoServer/database
      - usenet-couchpotato-db_backup:/CouchPotatoServer/db_backup
      - usenet-couchpotato-logs:/CouchPotatoServer/logs
      - usenet-sabnzbd-incomplete:/sabnzbd/Downloads/incomplete
      - usenet-sabnzbd-complete:/sabnzbd/Downloads/complete
      - usenet-library:/library
    networks:
      - services
    tty: true
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.tags=back"
        - "traefik.backend=usenet-couchpotato"
        - "traefik.frontend.entryPoints=http"
        - "traefik.frontend.rule=Host:usenet.hutter.cloud;PathPrefix:/couchpotato"
        - "traefik.protocol=http"
        - "traefik.docker.network=services"
        - "traefik.port=5050"

  sonarr:
    image: linuxserver/sonarr
    environment:
      PGID: '0'
      PUID: '0'
    stdin_open: true
    volumes:
      - usenet-sabnzbd-complete:/sabnzbd/Downloads/complete
      - usenet-sonarr-conf:/config
      - usenet-library-tv:/tv
      - usenet-library-tv-de:/tv_de
      - /dev/rtc:/dev/rtc:ro
    networks:
      - services
    tty: true
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.tags=back"
        - "traefik.backend=usenet-sonarr"
        - "traefik.frontend.entryPoints=http"
        - "traefik.frontend.rule=Host:usenet.hutter.cloud;PathPrefix:/sonarr"
        - "traefik.protocol=http"
        - "traefik.docker.network=services"
        - "traefik.port=8989"

  headphones:
    image: linuxserver/headphones
    environment:
      TZ: Europe/Zurich
    stdin_open: true
    volumes:
      - usenet-sabnzbd-complete:/downloads
      - usenet-library-music:/music
      - usenet-headphones-config:/config
    networks:
      - services
    tty: true
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.tags=back"
        - "traefik.backend=usenet-headphones"
        - "traefik.frontend.entryPoints=http"
        - "traefik.frontend.rule=Host:usenet.hutter.cloud;PathPrefix:/headphones"
        - "traefik.protocol=http"
        - "traefik.docker.network=services"
        - "traefik.port=8181"
