version: '3.4'

networks:
  connectivity:
    external:
      name: connectivity

volumes:
  connectivity-letsencrypt-etc:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.hutter.cloud,rw,nolock,async
      device: ":/volume1/docker/connectivity-letsencrypt"

secrets:
  aws-key:
    file: ./secrets/aws-key
  aws-secret:
    file: ./secrets/aws-secret

services:
  reverse-proxy:
    image:  sebastianhutter/haproxy:latest
    networks:
      - connectivity
    environment:
      CONFIG_URL: http://nas.hutter.cloud/dnas/docker/connectivity/haproxy.cfg
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - connectivity-letsencrypt-etc:/etc/letsencrypt

  certbot:
    image: sebastianhutter/certbot:latest  
    environment:
      DOMAIN: usenet.hutter.cloud,calibre.hutter.cloud
      EMAIL: mail@sebastian-hutter.ch
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ACCESS_KEY_ID: /run/secrets/aws-key
      AWS_SECRET_ACCESS_KEY: /run/secrets/aws-secret
    secrets:  
      - aws-key
      - aws-secret
    volumes:
      - connectivity-letsencrypt-etc:/etc/letsencrypt