version: '3.4'

networks:
  connectivity:
    external:
      name: connectivity
  services:
    external:
      name: services

volumes:
  connectivity-letsencrypt-nas-etc:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.hutter.cloud,rw,nolock,async
      device: ":/volume1/docker/connectivity-letsencrypt-nas"
  connectivity-traefik:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.hutter.cloud,rw,nolock,async
      device: ":/volume1/docker/gocd-traefik"

secrets:
  aws-key:
    file: ./secrets/aws-key
  aws-secret:
    file: ./secrets/aws-secret
  swarm-ca:
    file: ./secrets/swarm-ca
  swarm-key:
    file: ./secrets/swarm-key
  swarm-cert:
    file: ./secrets/swarm-cert

services:
  authentication:
    image: sebastianhutter/nginx
    networks:
      - services
      - connectivity
    stdin_open: true
    tty: true
    environment:
      CONFIG_URL: http://nas.hutter.cloud/dnas/docker/connectivity/nginx.conf
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.tags=front"
        - "traefik.backend=authentication"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.rule=Host:calibre.hutter.cloud,status.hutter.cloud,usenet.hutter.cloud"
        - "traefik.protocol=http"
        - "traefik.docker.network=connectivity"
        - "traefik.port=80"

  traefik-front:
    image:  sebastianhutter/traefik:front
    networks:
      - connectivity
    environment:
      AWS_REGION: eu-central-1
      AWS_HOSTED_ZONE_ID: Z3CBRYU3UXXFKT
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 12001:8080/tcp
    volumes:
      - connectivity-traefik:/acme
    secrets:
      - aws-key
      - aws-secret
      - swarm-ca
      - swarm-cert
      - swarm-key
    command: --constraints="tag==front"

  traefik-back:
    image:  sebastianhutter/traefik:back
    networks:
      - services
    environment:
      AWS_REGION: eu-central-1
      AWS_HOSTED_ZONE_ID: Z3CBRYU3UXXFKT
    ports:
      - 12003:8080/tcp
    volumes:
      - connectivity-traefik:/acme
    secrets:
      - aws-key
      - aws-secret
      - swarm-ca
      - swarm-cert
      - swarm-key
    command: --constraints="tag==back"

  # create certificate for nas.hutter.cloud 
  # needs manual renewal all 90 days
  certbot-nas:
    image: sebastianhutter/certbot:latest  
    environment:
      DOMAIN: nas.hutter.cloud
      EMAIL: mail@sebastian-hutter.ch
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ACCESS_KEY_ID: /run/secrets/aws-key
      AWS_SECRET_ACCESS_KEY: /run/secrets/aws-secret
    secrets:  
      - aws-key
      - aws-secret
    volumes:
      - connectivity-letsencrypt-nas-etc:/etc/letsencrypt