version: '3.4'


networks:
  services:
    external:
      name: services
  # calibre:
  #   driver: overlay

volumes:
  calibre-privat-library:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.hutter.cloud,rw,nolock,async
      device: ":/volume1/calibre/personal"

services:
  privat:
    image: sebastianhutter/calibreserver:latest
    stdin_open: true
    volumes:
        - calibre-privat-library:/library
    tty: true
    networks:
      - services
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.tags=back"
        - "traefik.backend=calibre-privat"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.rule=Host:calibre.hutter.cloud,PathStrip:/sebastian/"
        - "traefik.protocol=http"
        - "traefik.docker.network=services"
        - "traefik.port=80"
