version: '3.4'

networks:
  services:
    external:
      name: services

secrets:
  checkhttp-user:
    file: ./secrets/checkhttp-user
  checkhttp-pass:
    file: ./secrets/checkhttp-pass

services:
  statuspage:
    image: sebastianhutter/checkhttp:latest
    environment:
      CHECKHTTP_YAML_FILE: http://nas.barfoot.local/dnas/docker/status/checkhttp.yml
      CHECKHTTP_WAIT_TIME: 300
      CHECKHTTP_HTTP_USER: /run/secrets/checkhttp-user
      CHECKHTTP_HTTP_PASS: /run/secrets/checkhttp-pass
    stdin_open: true
    tty: true
    networks:
      - services
    secrets:  
      - checkhttp-user
      - checkhttp-pass
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.tags=back"
        - "traefik.backend=status"
        - "traefik.frontend.entryPoints=http"
        - "traefik.frontend.rule=Host:status.hutter.cloud"
        - "traefik.protocol=http"
        - "traefik.docker.network=services"
        - "traefik.port=8080"
