version: '3.4'

networks:
  connectivity:
    external:
      name: connectivity
  vault:
    driver: overlay

secrets:
  aws-key:
    file: ./secrets/aws-key
  aws-secret:
    file: ./secrets/aws-secret

volumes:
  vault-server:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.hutter.cloud,rw,nolock,async
      device: ":/volume1/docker/vault-vault-server"
  vault-letsencrypt-etc:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.hutter.cloud,rw,nolock,async
      device: ":/volume1/docker/vault-letsencrypt"


services:
  reverse-proxy:
    image:  sebastianhutter/haproxy:latest
    networks:
      - connectivity
      - vault
    environment:
      CONFIG_URL: http://nas.hutter.cloud/dnas/docker/vault/haproxy.cfg
      SSL_CERTIFICATE: /etc/letsencrypt/live/vault.hutter.cloud/haproxy.pem
    ports:
      - 8200:8200/tcp
    volumes:
      - vault-letsencrypt-etc:/etc/letsencrypt

  certbot:
    image: sebastianhutter/certbot:latest  
    environment:
      DOMAIN: vault.hutter.cloud
      EMAIL: mail@sebastian-hutter.ch
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ACCESS_KEY_ID: /run/secrets/aws-key
      AWS_SECRET_ACCESS_KEY: /run/secrets/aws-secret
    secrets:  
      - aws-key
      - aws-secret
    volumes:
      - vault-letsencrypt-etc:/etc/letsencrypt

  vault-server:
    cap_add:
    - IPC_LOCK
    image: vault
    environment:
      VAULT_LOCAL_CONFIG: '{ "backend": { "file": { "path": "/vault/hutter.cloud"
        } }, "listener": { "tcp": { "address": "0.0.0.0:8200", "tls_disable": true } }, "default_lease_ttl":
        "168h", "max_lease_ttl": "720h", "disable_mlock": true }'
    stdin_open: true
    volumes:
      - vault-server:/vault
    networks:
      - vault
    tty: true
    command:
      - vault
      - server
      - -config
      - /vault/config

